#!/usr/bin/env python3
"""Pull vocab generated by real visitors from the live production API and
merge it into articles.db's vocab table. Production's articles.db is
baked into the Docker image at build time (see AGENTS.md) — anything
generated on-demand only lives in that running container's writable
layer and is wiped on the next redeploy. This never generates anything
itself; it only persists what real visitors already triggered on the
live site, so this stays safe and cheap to run daily."""
import json
import sys
import urllib.request

import db

DEFAULT_EXPORT_URL = "https://cpoint.paklau.com/api/admin/vocab"

# cpoint.paklau.com is Cloudflare-proxied, and Cloudflare's Bot Fight Mode
# specifically blocklists urllib's default "Python-urllib/x.y" User-Agent
# with a 403 (confirmed: any other UA, even "python-requests/...", passes
# fine — this isn't an IP/ASN block on GitHub Actions' runners, just that
# one signature). This is what killed this workflow's first scheduled run.
USER_AGENT = "cPoint-vocab-sync/1.0 (+https://github.com/lsrepo/cPoint)"


def fetch_export(export_url):
    req = urllib.request.Request(export_url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as res:
        return json.load(res)


def sync(export_url, db_path):
    rows = fetch_export(export_url)

    conn = db.connect(db_path)
    synced = 0
    for row in rows:
        nid = row["nid"]
        if not db.article_exists(conn, nid):
            # Production can briefly be ahead of this repo's articles.db
            # (e.g. an article synced there but not yet here) — skip
            # rather than violate the FK constraint on vocab.article_nid.
            continue
        db.save_vocab(conn, nid, row["terms"], row["generated_in_seconds"])
        synced += 1
    conn.close()
    return synced


def main():
    export_url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_EXPORT_URL
    synced = sync(export_url, db.DB_PATH)
    print(f"Vocab sync complete: {synced} row(s) merged.")


if __name__ == "__main__":
    main()
